### ISSUE TITLE
Confused about input_file and input_data in Tables file, what exactly is in the Tables file?

### ISSUE THREAD

**Issue by yxywalab** [TAMUGeorgeGroup/COMET#1]
Hi，
   I want to know which files I should prepare in the tables folder. I have read your article and guidence, and I know that I need to include a csv file with three columns, "Sample", "DataPath", and "MetaData", And a DATATABLETEST.csv, but I don't know if the datatabletest is the csv table for these three columns. I would appreciate it if you could provide more details.
Thanks.

**Comment by yxywalab** [comment]
I read the original code of the COMET function, and I think I have a basic understanding of what you are referring to. Though, I would appreciate it if you could provide further guidance and simplify the explanation.

**Comment by AnniceNajafi** [comment]
> I read the original code of the COMET function, and I think I have a basic understanding of what you are referring to. Though, I would appreciate it if you could provide further guidance and simplify the explanation.

Hi yxywalab, that is correct. You are supposed to have a csv file with the three columns you mentioned. They should store the name of the data matrix and the metadata files which are stored in a directory named "Input_Data". 

Suppose your main working directory is COMET_STAR_Protocol, then this is how your directory should be structured:
<ul>
<li><strong>COMET_STAR_Protocol (working directory)</strong></li>
       <ul>
       <li>-Input_Data</li>
<ul>
  <li>-meta_data.csv.gz</li>
  <li>-matrix.csv.gz</li>
</ul>
<li>-Tables</li>
<ul>
    <li>-DATATABLETEST.csv (with columns named "Sample", "DataPath", and "MetaData". you should store <sample_name>, matrix.csv.gz, meta_data.csv.gz in that file)</li>
</ul>
</ul>
</ul>    
Please let me know if you need help with anything else. 
Thanks,
Annice

**Comment by yxywalab** [comment]
Your guidance is very detailed, and I have successfully run the pipeline. Thank you again for your research and help.

**Comment by AnniceNajafi** [comment]
> Your guidance is very detailed, and I have successfully run the pipeline. Thank you again for your research and help.

No Problem! There is also a web-based app, <a href=https://najafiannice.shinyapps.io/EMT_app_trial/_w_5bf1110f/>shinyCOMET</a> that doesn't assume symmetric transition rates into the hybrid state. The final version will have the original MLR and KS scoring methods for microarray data as well but for now I have commented them out. It only runs COMET once and does not compare it to the flow cytometry data with DTW (obviously that cannot be done on a web app) but you can still experiment with changing the number of highly variable genes. There is an example dataset in the 'more' tab and you can login with username 'guest' and password '1234'.

Cheers,
Annice

**Comment by yxywalab** [comment]
Hello Annice,

I have a question regarding the unexpectedly long runtime of the pipeline, which took 10 days to complete, far exceeding the estimated time in the protocol. I wonder if there might be any factors that I overlooked. Your help would be greatly appreciated.
By the way，my dataset consists of 9994 objects and 33000 genes.

Warm regards,
yxywalab

**Comment by AnniceNajafi** [comment]
> Hello Annice,
> 
> I have a question regarding the unexpectedly long runtime of the pipeline, which took 10 days to complete, far exceeding the estimated time in the protocol. I wonder if there might be any factors that I overlooked. Your help would be greatly appreciated. By the way，my dataset consists of 9994 objects and 33000 genes.
> 
> Warm regards, yxywalab

Hello yxywalab, 

Thank you for your message. The run time can vary depending on your computer's specifications. I wouldn't think the number of genes would be the primary reason because we filter for EMT genes. You can make the pipeline run faster if the code is parallelized over cores. I had parallelized the code initially but did not include it in the R package thinking the package would be more straightforward to use without it. I will add a function for doing this to the package in a couple of days. 

Also could you please let me know which step of the pipeline takes the longest to run and the specifications of your computer?

I will notify you once this update is available. In the meantime, if you have any other questions or need further clarification, please feel free to reach out.

Thanks,
Annice

**Comment by yxywalab** [comment]
Hello, Annice, 
Thank you for your concern about my problem.  It took me up to 4 minutes to run PCA, Calculated graph and diffusion operator and Calculated MAGIC, which limited my speed. I'm running on a server with 256GB of memory on 20 cores, but the footprint is not high. I would appreciate it if you could solve this problem. 
Thank you，
yxywalab

**Comment by AnniceNajafi** [comment]
> Hello, Annice, Thank you for your concern about my problem. It took me up to 4 minutes to run PCA, Calculated graph and diffusion operator and Calculated MAGIC, which limited my speed. I'm running on a server with 256GB of memory on 20 cores, but the footprint is not high. I would appreciate it if you could solve this problem. Thank you， yxywalab

I am very sorry that you are facing this issue. That could be because the code is not properly optimized for parallel processing and it would run a lot faster if parallelized over cores. However, I would still not expect it to take 10 days to complete for ~10k cells. I am suspecting there may be other issues. Have you tried running the example dataset included in the protocol (on Zenodo) on the server you are using? If so could you please let me know how long it takes for you to run only the A549 TGFB sample? Could you describe how you're allocating resources for the process? Is the 10 day completion time only for one sample with ~10k cells or multiple samples? 

Please let me know so I can have a better understanding of the situation.
Thanks,
Annice

**Comment by yxywalab** [comment]
I executed the A549 sample on the server, which required 2 minutes to process one sample, while it took 8-10 minutes to process my own data. I only ran my 10,000-cell sample, without any additional tasks. I believe that utilizing parallelized cores may be crucial, but there could also be specific data formatting requirements. Upon comparing the example data with my own data, the sole disparity is that the example data contains 3,568 genes, while my dataset contains ten times that amount.
Thanks，
yxywalab

**Comment by AnniceNajafi** [comment]
> I executed the A549 sample on the server, which required 2 minutes to process one sample, while it took 8-10 minutes to process my own data. I only ran my 10,000-cell sample, without any additional tasks. I believe that utilizing parallelized cores may be crucial, but there could also be specific data formatting requirements. Upon comparing the example data with my own data, the sole disparity is that the example data contains 3,568 genes, while my dataset contains ten times that amount. Thanks， yxywalab

Thanks for clarifying that. I think there may be a misunderstanding. The sample dataset consists of 13239 genes and 3,568 cells for A549 and TGFB. I think a discussion could help clarify any confusion. If you would like to have a virtual meeting you can reach me at annicenajafi@tamu.edu to arrange a suitable time. 

Thanks,
Annice

**Comment by yxywalab** [comment]
Thank you for your kind assistance. I believe the root of my issue lies in not employing parallel processing to run the program, and I am currently exploring the use of parallel to optimize the code's performance. I also see the virtual meeting you suggested as a viable solution to the problem. I will implement parallel processing as soon as possible. If it is not successful, I will seek your guidance. Thank you once again for your support. Your kindness is truly appreciated.

Warm regards,
yxywalab

**Comment by AnniceNajafi** [comment]
> Thank you for your kind assistance. I believe the root of my issue lies in not employing parallel processing to run the program, and I am currently exploring the use of parallel to optimize the code's performance. I also see the virtual meeting you suggested as a viable solution to the problem. I will implement parallel processing as soon as possible. If it is not successful, I will seek your guidance. Thank you once again for your support. Your kindness is truly appreciated.
> 
> Warm regards, yxywalab

No problem! hopefully the problem will be solved soon. I will post the update regarding parallelizing the code on a Github repo on my personal page in a few days because I cannot push any changes to this repo anymore @jasontgeorge. 

Thanks,
Annice

**Comment by AnniceNajafi** [comment]
Hello Yi @yxywalab, 

Per your request, I have updated the package and have added parallelization. Please refer back to my Github page at <a href=https://github.com/AnniceNajafi/COMET>this link</a> and follow the instructions to run the pipeline. 

Thanks,
Annice
